name: C++ CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build C++ code
        run: g++ -o hello-world main.cpp

      - name: Run tests
        run: ./hello-world
